version: 2
jobs:
  build:
#    docker:
#      - image: circleci/node:1.2.0
    machine:
      image: ubuntu-2204:current
    branches:
      only:
        - master
    steps:
#      - checkout
      - run:
          name: test...
          command: echo "Testing..."
      - run:
          name: Run tests
          command: echo "Running tests..."
      - run:
          name: Build project
          command: echo "Building project..."
      - run:
          name: check pwd
          command: pwd
      - run:
          name: check ls
          command: ls