version: 2
jobs:
  build:
#    docker:
#      - image: circleci/node:1.2.0
    machine:
      image: ubuntu-2204:current
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: test...
          command: echo "Testing..."
      - run:
          name: check pwd
          command: pwd
      - run:
          name: check ls
          command: ls
      - run:
          name: check ls
          command: ls -la
      - run:
          name: mvn clean
          command: mvn clean
      - run:
          name: mvn compile
          command: mvn compile
      - run:
          name: mvn package
          command: mvn package
      - run:
          name: ls target
          command: ls target
      - run:
          name: jps
          command: jps